### ISSUE TITLE
when infinite-scroll-immediate-check is false the $interval function is called infinitely

### ISSUE THREAD

**Issue by david-gang** [sroze/ngInfiniteScroll#255]
Here is the code:
```javascript
return checkInterval = $interval((function() {
          if (immediateCheck) {
            return handler();
          }
        }), 0);
```

When immediatecheck is true, the handler function is called, and interval is canceled.
When not the $interval function is called infinitely.
Please look here: https://docs.angularjs.org/api/ng/service/$interval

So we have here an infinite loop in the browser which is bad.

What is even worse, that we are calling digest cycles infinitely.

The easiest solution is to change the javascript code:

```javascript
 function getFirstFunction(immediateCheck) {
          if(immediateCheck) {
            return  $interval((function() {
                return handler();
            }), 0)
          }
          else {
            return false;
          }


        }
        return checkInterval = getFirstFunction(immediateCheck);
```

Sorry that i don't make a pull request: I don't know cofee script.

**Comment by david-gang** [comment]
Update: I see it was fixed with release 1.2.2. Closing it

**Comment by belfz** [comment]
Where is version 1.2.2? I only see version 1.2.1 and this problem still persists.

**Comment by mlemainque** [comment]
+1
The problem persists on 1.2.2
Thanks @belfz for the fix which works well
